### ISSUE TITLE
pelican-bootstrap3: UndefinedError: 'gettext' is undefined

### ISSUE THREAD

**Issue by chan-y-park** [getpelican/pelican-themes#460]
Hi,

I tried using this pelican theme but it displays
`CRITICAL: UndefinedError: 'gettext' is undefined`
and fails to produce html files. I tried using a different theme and it works without a problem.

I am using pelican 3.6.3.

**Comment by chan-y-park** [comment]
Sorry, I wrote my post at a wrong place...

**Comment by justinmayer** [comment]
1. You did not mention which theme you are talking about.
2. Current version of Pelican is 3.7, so I suggest trying that before anything else.

**Comment by chan-y-park** [comment]
Sorry for the confusion; I thought that there is a separate issue page for each theme. The above error message comes out when I use pelican-bootstrap3.

**Comment by justinmayer** [comment]
Just merged several commits related to that theme, so I suggest using git-bisect to determine which Git IDs work and which do not.

**Comment by chan-y-park** [comment]
Thanks for your help, I tried git-bisect between the first commit and the current commit and git says b6ab2ad418b634eda366026855be0574703281d7 is the first bad commit.

**Comment by chan-y-park** [comment]
Hmm, I am not sure if I used git-bisect in a correct way; I tried checking a few commits by hand and the latest commit that works is be36234f9f7fb4633d7e2eee89833839d7cbf1eb.

By the way, I cannot use pelican 3.7, somehow `render_math` plug-in does not work with pelican 3.7.

**Comment by gravyboat** [comment]
I ran into this today as well after swapping over to the pelican-themes repo. I'm running this on the `3.7.0` release (just upgraded today) and am getting the same error. Originally it was `UndefinedError: '_'` is undefined, which was an issue because I didn't have `python-gettext` installed. After installing that and adding `JINJA_EXTENSIONS = ['jinja2.ext.i18n']` it now notes that `gettext` is missing instead.

**Comment by gravyboat** [comment]
I rolled the theme repo back to https://github.com/getpelican/pelican-themes/commit/be36234f9f7fb4633d7e2eee89833839d7cbf1eb#diff-0eb6cb930365747af1fe070650593b8e (the commit prior to the translation one) and it works fine.

**Comment by gravyboat** [comment]
@chan-y-park Try installing `python-gettext` and see if that fixes the error for you.

**Comment by jranke** [comment]
The translation feature was developed using pelican 3.6.3 and it used to work for me. Sorry for the inconvenience. I just upgraded to pelican 3.7.0 and got the error about  `JINJA-EXTENSIONS` being outdated. My next step was to use
`JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}`.

Then I still got an error `KeyError: 'JINJA_EXTENSIONS'`  when using the `i18n_subsites` plugin. So I disabled this plugin, and now I also get `UndefinedError: 'gettext' is undefined`. I have `python-getttext` installed, so somehow it is not being found/loaded.

**Comment by jranke** [comment]
Obviously `gettext` needs to be installed into the jinja environment using a call to
`jinja2.Environment.install_gettext_callables` as documented [here](http://jinja.pocoo.org/docs/dev/extensions/).

However, I do not know how to access the environment that is created with configuration option `JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}`.

**Comment by gravyboat** [comment]
@jranke No worries it's not like you hatched a devious plot to break it on this release! I tried something similar to what you did (setting the `ENVIRONMENT`) variable and it didn't seem to work. I think if we can determine how the mapping works between the `JINJA_ENVIRONMENT` setting and the old `JINJA_EXTENSIONS` we can probably resolve the error, I'm just not familiar enough with the internals to know what that mapping looks like.

**Comment by jranke** [comment]
@gravyboat Thanks for the heads-up! This translation stuff seems not to be used so much in pelican themes...

**Comment by jranke** [comment]
For what it's worth, I just downgraded pelican to 3.6.3 (from Debian jessie-backports), went back to the previous configuration using `JINJA_EXTENSIONS` and `pelican-bootstrap3` from current master works with this setting. So I wonder why @chan-y-park had this problem with pelican 3.6.3.

**Comment by jranke** [comment]
It seems to me that this needs to be taken care of in pelican itself, so gettext (and maybe newgettext) can be installed via the pelican config file.

**Comment by justinmayer** [comment]
> Obviously gettext needs to be installed into the jinja environment using a call to
jinja2.Environment.install_gettext_callables as documented here.

> However, I do not know how to access the environment that is created with configuration option JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}.

This seems to be the relevant question. Any thoughts, @rjames86?

**Comment by rjames86** [comment]
@justinmayer how was this handled previously? Looks like this isn't a new problem: https://github.com/pallets/jinja/issues/363

In my quick testing in local, adding this to `generators.py` fixed the problem, but I don't have enough context on the i18n use cases to know if this covers everything:

```
# On line 71 in generators.py
import gettext
self.env.install_gettext_translations(gettext)
```

**Comment by jranke** [comment]
Thanks for having a look. I thought it would need to be `install_gettext_callables`, as mentioned above? But I have not done any tests and have no context either...

**Comment by rjames86** [comment]
>Thanks for having a look. I thought it would need to be install_gettext_callables, as mentioned above But I have not done any tests and have no context either...

That also very well could be. Does anyone else in this thread use the i18n extension that could verify using either one fixes everything? Pelican successfully builds my site when using `install_gettext_translations`, but I don't know if if solves issues further downstream in the templates.

Just for completeness, I tested this on both 3.6.3 and 3.7 and the error is the same. I'm confident that this is not related to [#1999](https://github.com/getpelican/pelican/pull/1999). However, happy to figure out a good fix for this going forward.

**Comment by jranke** [comment]
Maybe it is just the jinja version that's causing the difference. I can't test right now, but I have a website using i18n, so I hope to be able to test your proposed fix in the next couple of days.

**Comment by chan-y-park** [comment]
Dear all, thank you very much for your efforts in trying to resolve this issue!

@jranke I doubled-checked with pelican 3.6.3 + current master and I do get the error I mentioned in the first place, then I checked out be36234f9f7fb4633d7e2eee89833839d7cbf1eb and it works fine.

I am running this on a conda environment, so let me post it here just in case there is any dependency I am missing.

```
# packages in environment at /home/chan/anaconda2/envs/python2:
#
_nb_ext_conf              0.3.0                    py27_0  
anaconda-client           1.5.1                    py27_0  
backports                 1.0                      py27_0  
backports-abc             0.4                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
backports_abc             0.4                      py27_0  
blinker                   1.4                       <pip>
bokeh                     0.10.0                   py27_0  
cairo                     1.12.18                       6  
certifi                   2016.2.28                 <pip>
click                     6.6                       <pip>
click                     6.6                      py27_0  
clyent                    1.2.2                    py27_0  
jupyter_contrib_core      0.3.0                    py27_0    conda-forge
jupyter_contrib_nbextensions 0.1.0                    py27_0    conda-forge
jupyter_nbextensions_configurator 0.2.1                    py27_2    conda-forge
psutil                    4.3.0                    py27_0    conda-forge
configparser              3.5.0                    py27_0  
cycler                    0.10.0                    <pip>
cycler                    0.10.0                   py27_0  
decorator                 4.0.10                    <pip>
decorator                 4.0.10                   py27_0  
docutils                  0.13.1                    <pip>
entrypoints               0.2.2                    py27_0  
enum34                    1.1.6                    py27_0  
feedgenerator             1.9                       <pip>
flake8                    2.5.1                    py27_0  
Flask                     0.11.1                    <pip>
flask                     0.11.1                   py27_0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
get_terminal_size         1.0.0                    py27_0  
ghp-import                0.4.1                     <pip>
glib                      2.43.0                        1  
harfbuzz                  0.9.39                        1  
ipykernel                 4.2.2                     <pip>
ipykernel                 4.5.0                    py27_0  
ipython                   5.0.0                     <pip>
ipython                   5.1.0                    py27_0  
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.1.1                    py27_0  
itsdangerous              0.24                      <pip>
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
Jinja2                    2.8                       <pip>
jinja2                    2.8                      py27_1  
jpeg                      8d                            2  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter-client            4.3.0                     <pip>
jupyter-client            4.4.0                     <pip>
jupyter-contrib-core      0.3.0                     <pip>
jupyter-core              4.2.0                     <pip>
jupyter-nbextensions-configurator 0.2.1                     <pip>
jupyter_client            4.3.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_core              4.2.0                    py27_0  
lcms                      1.19                          0  
libffi                    3.2.1                         0  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         2  
libxml2                   2.9.2                         0  
llvmlite                  0.13.0                   py27_0  
Markdown                  2.6.7                     <pip>
MarkupSafe                0.23                      <pip>
markupsafe                0.23                     py27_2  
matplotlib                1.5.1               np111py27_0  
mccabe                    0.3.1                    py27_0  
mistune                   0.7.2                    py27_0  
mkl                       11.3.3                        0  
mpmath                    0.19                      <pip>
nb_anacondacloud          1.2.0                    py27_0  
nb_conda                  2.0.0                    py27_0  
nb_conda_kernels          2.0.0                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.0.1                    py27_0  
nbpresent                 3.0.2                    py27_0  
networkx                  1.11                     py27_0  
notebook                  4.2.1                    py27_0  
numba                     0.28.1              np111py27_0  
numpy                     1.11.1                    <pip>
numpy                     1.11.1                   py27_0  
openssl                   1.0.2h                        1  
pandas                    0.18.1                    <pip>
pandas                    0.18.1              np111py27_0  
pango                     1.39.0                        1  
path.py                   8.2.1                    py27_0  
pathlib2                  2.1.0                     <pip>
pathlib2                  2.1.0                    py27_0  
graphviz                  2.38.0                        3    pdrops
pelican                   3.6.3                     <pip>
pep8                      1.7.0                    py27_0  
pexpect                   4.0.1                    py27_0  
pexpect                   4.2.0                     <pip>
pickleshare               0.7.3                     <pip>
pickleshare               0.7.3                    py27_0  
pil                       1.1.7                    py27_2  
pip                       8.1.2                    py27_0  
pip                       9.0.1                     <pip>
pixman                    0.32.6                        0  
prompt-toolkit            1.0.3                     <pip>
prompt_toolkit            1.0.3                    py27_0  
ptyprocess                0.5.1                     <pip>
ptyprocess                0.5.1                    py27_0  
pycairo                   1.10.0                   py27_0  
pyflakes                  1.2.3                    py27_0  
Pygments                  2.1.3                     <pip>
pygments                  2.1.3                    py27_0  
pygraphviz                1.3.1                     <pip>
pyparsing                 2.1.4                    py27_0  
pyparsing                 2.1.5                     <pip>
pyqt                      4.11.4                   py27_4  
python                    2.7.12                        1  
python-dateutil           2.5.3                     <pip>
python-dateutil           2.5.3                    py27_0  
python-dateutil           2.6.0                     <pip>
python-gettext            3.0                       <pip>
pytz                      2016.10                   <pip>
pytz                      2016.6.1                  <pip>
pytz                      2016.6.1                 py27_0  
PyYAML                    3.11                      <pip>
pyyaml                    3.11                     py27_4  
pyzmq                     15.3.0                    <pip>
pyzmq                     15.3.0                   py27_0  
pyzmq                     16.0.0                    <pip>
qt                        4.8.7                         4  
qtconsole                 4.2.1                    py27_0  
readline                  6.2                           2  
requests                  2.10.0                    <pip>
requests                  2.11.1                   py27_0  
scipy                     0.18.0              np111py27_0  
setuptools                26.1.1                   py27_0  
simplegeneric             0.8.1                     <pip>
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                   <pip>
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                    <pip>
six                       1.10.0                   py27_0  
smartypants               1.8.6                     <pip>
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
sympy                     1.0                       <pip>
terminado                 0.6                      py27_0  
tk                        8.5.18                        0  
tornado                   4.4.1                     <pip>
tornado                   4.4.1                    py27_0  
traitlets                 4.2.2                    py27_0  
traitlets                 4.3.1                     <pip>
typogrify                 2.0.7                     <pip>
Unidecode                 0.4.19                    <pip>
wcwidth                   0.1.7                     <pip>
wcwidth                   0.1.7                    py27_0  
Werkzeug                  0.11.10                   <pip>
werkzeug                  0.11.10                  py27_0  
wheel                     0.29.0                   py27_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.4                         0  
zlib                      1.2.8                         3  
```

**Comment by avaris** [comment]
Let me help here:

The setting change with 3.7 (`JINJA_ENVIRONMENT` vs `JINJA_EXTENSIONS`) *will not* cause a break as defined here. 

The issue is that, this "translation" feature was developed with the assumption that [`i18n_subsites`](https://github.com/getpelican/pelican-plugins/blob/master/i18n_subsites) plugin will be present, because that [does](https://github.com/getpelican/pelican-plugins/blob/master/i18n_subsites/i18n_subsites.py#L293) the installation for you. This interdependence isn't mentioned anywhere (I'm guessing, while developing @jranke wasn't aware of it either).

The problem arises when you don't have the plugin. It doesn't matter what version (3.6 or 3.7) you use. You'll get the error. And with 3.7, you can't use the plugin right now since it needs to be updated to the new setting.

**Comment by justinmayer** [comment]
Thanks for assisting with this, @avaris. Much appreciated.

@jranke: I wasn't aware of the introduction of a new dependency when merging your PR. Would you please consider preparing a new pull request that makes your I18N features optional? As you can imagine, not everyone needs that functionality, and it should probably be an opt-in feature.

**Comment by rjames86** [comment]
Thanks @justinmayer and @avaris. At least that validates my assumptions. My change would have no affect, but I didn't know how the i18n stuff worked.

**Comment by jranke** [comment]
@avaris and @justinmayer: I see it differently: Removing the setting `JINJA_EXTENSIONS` from the pelican config broke the i18n_subsites plugin.

**Comment by jranke** [comment]
I tried to communicate this in my last comment before the merge https://github.com/getpelican/pelican-themes/pull/441#issuecomment-266811378

**Comment by rjames86** [comment]
@jranke please take a look at [#1999](https://github.com/getpelican/pelican/pull/1999). You'll see that there is no fundamental difference between what was being done with `JINJA_EXTENSIONS` vs the new `JINJA_ENVIRONMENT`. The same kwargs are being passed into the environment as before as you can see here: https://github.com/getpelican/pelican/pull/1999/files#diff-1a5861ddd428e9eae60b911254e077b0

**Comment by jranke** [comment]
@rjames86 yes, but... `settings['JINJA_EXTENSIONS']` is gone, which the i18n_subsites plugin uses:
https://github.com/getpelican/pelican-plugins/blob/master/i18n_subsites/i18n_subsites.py#L273

**Comment by rjames86** [comment]
@jranke so going back to the original suggestion, this doesn't necessitate a change to core Pelican. There needs to be an update to the i18n_subsites plugin to pull extensions from the correct location

`generator.settings['JINJA_ENVIRONMENT']['extensions']`

See [settings.py](https://github.com/getpelican/pelican/blob/master/pelican/settings.py#L117)

**Comment by jranke** [comment]
@rjames86 agreed - should this be conditional on `generator.settings['JINJA_EXTENSIONS']` being present? I am not good at python, could you prepare a PR for the `i18n_subsites` plugin?

**Comment by jranke** [comment]
@rjames86 oooh, there are 77 open pull requests https://github.com/getpelican/pelican-plugins/pulls for that plugin...

**Comment by jranke** [comment]
@justinmayer Unfortunately, I do not see a way to make this feature optional, as all the templates are adapted to use` _()` for translating displayed strings. Feel free to roll back the commit, as it seems to give a lot of trouble to all of us...I can also maintain a separate branch on which I keep the translatable theme (that's what I have been doing for more than a year, the original pull request is quite old). Or we could fork the theme and have a translatable version.

**Comment by avaris** [comment]
I just submitted a [PR](https://github.com/getpelican/pelican-plugins/pull/818) to plugins repo updating `i18n_subsites` (+ some other that used the same setting).

But, that alone would not fix this issue. This plugin is still required to use the theme and that's not mentioned anywhere. Well, not necessarily `i18n_subsites` specifically. **A plugin** that installs the gettext translator is required. `i18n_subsites` happens to be one that does it.

**Comment by jranke** [comment]
@avaris You are fast, great! Wouldn't it make sense for pelican to take care of installing the gettext translator if the i18n jinja extension is loaded? I guess you all favor the status quo in pelican, so never mind. I am using the i18n subsites plugin anyways.

So to rescue the translation of this theme, I believe I should update the docs to clarify. In addition, maybe we could also define a function `_()` to just return its argument for the case that no translation of the templates is required? Then people would not have to activate the jinja extension and a plugin they do not use to use the theme.

**Comment by justinmayer** [comment]
@avaris: PR merged. Thanks!

@jranke: It would be nice to avoid reverting your changes, forking, etc, so anything you can do to make these features optional would be great. 👍

**Comment by avaris** [comment]
It doesn't make much sense to do it in `pelican` hardcoded, same as `jinja` itself doesn't do it automatically when you enable `'jinja2.ext.i18n'` extension. It can be configured and customized based on the needs.

However it might make sense to have a base plugin (something like `jinja_i18n`) that activates the extension and installs the translator. So, people who doesn't use `i18n_subsites` plugin can use that instead and have a working `i18n` environment.

**Comment by cranmer** [comment]
HI all! thanks for working on this. I've been struggling a bit with the 3.7 transition.
Can I suggest that the README for the theme reflects the current state. It took me a while to realize what are issues with themes, plugins, my own customizations, and my own mistakes.

**Comment by jranke** [comment]
@justinmayer Did you have a chance to look at my PR #465 ?
@cranmer Is it working at your end now?

**Comment by cranmer** [comment]
Hi @jranke thanks! There's a lot going on here. I see 
 * jinja2context: #818 for pelican-plugins
 *  #465 about `i18n_subsites`
 * and then #466 the big refactoring of the sidebar. 

To test do I need to implement all three?

I have a temporary hack that is working and not a ton of time for the rest of the week.

FYI: I'll probably send a PR for the theme later to support the `pelican_javascript` plugin, which I needed for this d3 enabled post: http://theoryandpractice.org/2016/12/collaboration-map/#

**Comment by ozak** [comment]
Hi I got the same error 

   UndefinedError: 'gettext' is undefined

under ``pelican 3.6`` and ``3.6.3``. I had installed ``3.7.`` but was running into the other problem mentioned. Was this resolved somehow?

**Comment by jranke** [comment]
Yes, and there is an open pull request #465 that documents this requirement to the README. However, I do not know of anyone except for @justinmayer that could merge the PR to save people from getting  the error and having to read through this issue.

**Comment by avaris** [comment]
I've been toying with this today. Here is what I have so far (Apologies in advance for the wall of text :)).

<hr>

I tried to get rid of any plugin requirement by trying to emulate a `gettext` function. So, I created a `gettext.html` in `includes` folder with this:

```jinja
{% if not gettext %}
    {% macro gettext(text) %}
        {{ text }}
    {% endmacro %}
{% else %}
    {% set gettext=gettext %}
{% endif %}
```

This puts a `gettext` macro that does absolutely nothing, if there isn't one. Then imported it in `base.html` with:

```jinja
{% from "includes/gettext.html" import gettext %}
```

This *almost* works.

 * AFAICS, any template that extends `base.html` has this. Take `article.html` for example. It will resolve `_(...)` calls without issues. 
 * Now, the next level: `article.html` includes `includes/article_info.html` which also has `_(...)` and they seem to work as well.
 * If we go deeper, `includes/article_info.html` also has its own includes like `includes/taglist.html`. _And this is the point it breaks_. `taglist.html` no longer has `gettext` (for some reason) and throws errors.

The solution is, re-importing the `gettext` for the includes. And this is the point this becomes less elegant. (Any suggestion from people who has more Jinja-fu than me is more than welcome.)

<hr>

Next, the plugin part. Here's a plugin-like class that you can simply put into your config file:

```python
class i18n(object):
    # looks for translations in
    # {LOCALE_DIR}/{LANGUAGE}/LC_MESSAGES/{DOMAIN}.mo
    # if not present, falls back to default    
    
    DOMAIN = 'messages'
    LOCALE_DIR = '{THEME}/translations'
    LANGUAGES = ['de']
    NEWSTYLE = True

    __name__ = 'i18n'

    def register(self):
        from pelican.signals import generator_init
        generator_init.connect(self.install_translator)

    def install_translator(self, generator):
        import gettext
        try:
            translator = gettext.translation(
                self.DOMAIN, 
                self.LOCALE_DIR.format(THEME=THEME), 
                self.LANGUAGES)
        except (OSError, IOError):
            translator = gettext.NullTranslations()
        generator.env.install_gettext_translations(translator, self.NEWSTYLE)
```

This will activate the German translation currently present in the theme. And you'll use it like:

```python
THEME = "/home/avaris/workspace/pelican-themes/pelican-bootstrap3"
JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}
PLUGINS = [i18n()]
```

If you change the `LANGUAGES` to `['en']` or any other non-existing translation, you should get the default (English) version. This can be easily modified into a proper plugin with settings, etc, so there will be more light-weight dependency than `i18n_subsites`.

BTW, besides being a replacement, this plugin by itself might have its own merit. It will enable the option for translatable themes (as long as people take the time to make/translate them).

<hr>

How to proceed from here is up to the users of this theme (And I'm **not** in that group). The options as I see are:

 * a (somewhat ugly) hack to remove dependencies
 * a lightweight dependency
 * a combination of both

**Comment by justinmayer** [comment]
Many thanks for your work on this, @Avaris. 👍 

What do users of this theme think about the latter proposed solutions?

**Comment by gravyboat** [comment]
It seems to me like the combo of both is the best. Personally I'm not very concerned about translations and I would prefer (based on the amount of work this has required) that the translation features be much more optional than it currently is as @avaris suggested, then themes can just enable translation if the plugin is detected and it's supported as part of the theme.

**Comment by jranke** [comment]
Using the dummy gettext macro thankfully proposed by @avaris would get rid of the dependency on any i18n plugin. Any theme that would like to be translatable could ship it, and include it in base.html and  any further template files that have translated includes. To me this would be a nice next step to avoid that theme users need to bother with anything i18n-related if they do not want to use it.

**Comment by meatballs** [comment]
What's the best to deal with this at the moment? I've just attempted to update a site that was using a very old version of the theme and hit all the problems listed above. I don't have any need of any translation.

**Comment by jranke** [comment]
Sorry for the trouble. This is documented meanwhile in the README of this theme:

Point the THEME variable in your pelicanconf.py to /path/to/pelican-bootstrap3 and add

    JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}

to your Pelican configuration, as this template can be translated (see Translations below). You also need to activate a plugin that initializes the i18n jinja extension. One possibility is an up to date version of the i18n_subsites plugin:

    PLUGIN_PATHS = ['/path/to/git/pelican-plugins'] PLUGINS = ['i18n_subsites']

**Comment by jodumont** [comment]
I resolve this by 

1. git clone https://github.com/getpelican/pelican-plugins.git pelican-plugins

2. adding in pelicanconf.py

```
PLUGIN_PATHS = ['/path/to/git/pelican-plugins', ]
PLUGINS = ['i18n_subsites', ]
JINJA_ENVIRONMENT = {
    'extensions': ['jinja2.ext.i18n'],
}
```

obviously you need to change the '/path/to/git/ part ;)

**Comment by rabernat** [comment]
I just hit this error on a production website which I thought had a stable environment. I am building in travis, and builds on commits that previously succeeded are now failing:
https://travis-ci.org/rabernat/research_computing_2018/builds/452429652

My environment is created by `pip install doctr pelican jupyter ipython nbconvert beautifulsoup4 markdown`

I'm trying to figure out what changed...

Repo is here: https://github.com/rabernat/research_computing_2018

**Comment by justinmayer** [comment]
Given that I just released Pelican 4.0 an hour or so ago, I doubt the timing is coincidental.

Assuming the events are related... For production environments, recommended practice is to pin your dependencies so that software upgrades do not result in unexpected changes, allowing you to upgrade your dependencies at a time that’s convenient — and anticipated — for you.

**Comment by avaris** [comment]
`i18n_subsites` needs an update for Pelican 4.0 (see getpelican/pelican-plugins#953).

**Comment by NickleDave** [comment]
I am running into this error with multiple versions of pelican (3.6., 3.7, 4.0, 4.0.1) on Ubuntu.

In spite of following all the instructions in the pelican-bootstrap3 README (enable `i18n_subsites` plugin, make sure jinja environment is set up correctly), I still get 
'''
UndefinedError: 'gettext' is undefined
'''

I'm using conda; I have conda environments in Windows where this works, but I would rather be running the latest version of everything on Ubuntu if possible.

Can someone summarize for a dumb person like me what the crucial issue is here?
Is it that all the jinja templates in pelican-bootstrap3 have `i18n` integrated so there's no easy way to just make it optional?

I have a couple sites running with this theme and I really like it. Seems like it's very fragile though and probably not friendly to anyone who isn't fluent in all the stuff that pelican tries to abstract away.

In case it helps I'm attaching the environment.yml for my conda environment, but like I said I've tried multiple versions of pelican and I still get the same error.
[environment.txt](https://github.com/getpelican/pelican-themes/files/3029703/environment.txt)
(it's an `environment.yml` file but GitHub isn't happy with that extension)

**Comment by NickleDave** [comment]
FWIW I was able to hack my way around this by doing a `pip install -e` of the Pelican source and adding the following right after `self.env` is defined in `./pelican/generators.py` as @rjames86 did above:
```
import gettext
self.env.install_gettext_translations(gettext)
```

i.e., here:
https://github.com/getpelican/pelican/blob/de71f39232947014149436a4205029d3a1b39f3e/pelican/generators.py#L77

**Comment by simonm3** [comment]
Any solution for this?

**Comment by jranke** [comment]
Works over here with pelican v4. Did you take the steps from https://github.com/getpelican/pelican-themes/issues/460#issuecomment-346652986 ?

**Comment by ksze** [comment]
Does

> I resolve this by
> 
>     1. git clone https://github.com/getpelican/pelican-plugins.git pelican-plugins
> 
>     2. adding in pelicanconf.py
> 
> 
> ```
> PLUGIN_PATHS = ['/path/to/git/pelican-plugins', ]
> PLUGINS = ['i18n_subsites', ]
> JINJA_ENVIRONMENT = {
>     'extensions': ['jinja2.ext.i18n'],
> }
> ```
> 
> obviously you need to change the '/path/to/git/ part ;)

Does this mean I no longer need the workaround from https://github.com/getpelican/pelican-themes/issues/460#issuecomment-269821765?

**Comment by jranke** [comment]
That workaround you are referring to was designed to avoid the need for using the i18n_subsites plugin which activates the jinja extension but would otherwise not be needed if you do not use translated subsites.
